######################################################################
# Automatically generated by qmake (3.1) Fri May 12 19:33:46 2017
######################################################################

TEMPLATE = subdirs
#TARGET = CoreWar

SUBDIRS += \
    CoreWarTests.pro \
	CoreWarApp.pro
