######################################################################
# Automatically generated by qmake (3.1) Fri May 12 19:43:56 2017
######################################################################

QT += testlib
#TARGET = CoreWarTests
INCLUDEPATH += .

HEADERS += \
		src/Assembler.hpp \
		src/Tokenizer.hpp \
		src/VirtualMachine.hpp

SOURCES += \
		src/Assembler.cpp \
		src/Tokenizer.cpp \
		src/VirtualMachine.cpp \
		tests/CoreWarTests.cpp

CONFIG += c++11
